version: '3.9'

services:
  server:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./chroma_data:/chroma/chroma
    ports:
      - 8000:8000
    environment:
      - IS_PERSISTENT=TRUE